ezsystem.connection {
   servers:[ 
	{
	    type: "HTTP"
	    name: "EZ Central service HTTP"
	    port: 6568
	    pool-size: 10
	    max-pool-size: 100
	    queue-size: 100
	}
	{
	    type: "WEB-SOCKET"
	    name: "EZ Central service Web Socket"
	    port: 6570
	    pool-size: 10
	    max-pool-size: 100
	    queue-size: 100
	}

    ]
}
